# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    step:
      - name: SonarQube Scan
      # You may pin to the exact commit or the version.
      # uses: kitabisa/sonarqube-action@513476d3b8845ec1776adaf7e1314019e5151e00
      uses: kitabisa/sonarqube-action@v1.2.0
      with:
        # SonarQube server URL.
        host: 
        # The project's unique key. Allowed characters are: letters, numbers, -, _, . and :, with at least one non-digit.
        projectKey: # optional, default is 
        # Name of the project that will be displayed on the web interface.
        projectName: # optional, default is 
        # The project version.
        projectVersion: # optional, default is 
        # Set the sonar.projectBaseDir analysis property.
        projectBaseDir: # optional, default is .
        # Login or authentication token of a SonarQube user.
        login: 
        # Password that goes with the sonar.login username. This should be left blank if an authentication token is being used.
        password: # optional
        # Encoding of the source code.
        encoding: # optional, default is UTF-8

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    
